### ISSUE TITLE
Handling plurals in intake.php

### ISSUE THREAD

**Issue by AardWolf** [m-h-c-t/mh-hunt-helper#110]
We can handle plurals consistently no matter the version of the extension if we do it in intake.php in a particular manner:

1. Add a column to the loot table for the plural name of the item.
2. Modify the intake query to be `SELECT id FROM loot WHERE name LIKE ? or plural_name LIKE ?` using the same argument value.
3. Procedurally as a single transaction (to avoid the query in 2 from getting multiple rows without fudging it by adding a `MIN` or something):
3A. Update loot row to set plural name.
3B. Get loot_id for plural entry in loot table.
3C. Get loot_id for singular entry in loot table.
3D. Update hunt_loot to change plural loot_id to singular loot_id
3E. Delete plural loot_id from loot table.

3 becomes something like:
```
update loot set plural_name = 'Plural Name' where name = 'Singular Name';
update hunt_loot set loot_id = (select id from loot where name = 'Singular Name')
where loot_id = (select id from loot where name = 'Plural Name');
delete from loot where name = 'Plural Name');
commit;
```

**Comment by AardWolf** [comment]
Alternatively if we can get multiple plural forms or the extension is too aggressive in de-pluralizing then we can make this a separate table - loot_plurals. It would have loot_id and plural_name as columns. It would get a row for each weird plural form we see.

**Comment by DevJackSmith** [comment]
i would say lets definitely keep our formatting logic out of sql, it's already complex enough. I would prefer it stay in javascript because it takes the load of server and that's where the rest of the logic lives. The only logic we have in php is the one that absolutely has to be there, like security or api. But since plurals do keep changing frequently and it's faster to change it on the server, i would agree to put it in PHP.

That being said, i think it should be translation associative arrays to translate it faster.

**Comment by DevJackSmith** [comment]
we can try it in db, but we need to be very careful that it doesn't slow down the performance even further, and doesn't break any other queries.

**Comment by DevJackSmith** [comment]
I was thinking we can do this in two steps:
1. we add optional field plural_name to the db, and in javascript we add another field to send to the server (plural_loot_name) if amount is >1. When server receives it, it uses normal name to record the hunt, but then in addition to that updates plural_name field if it's passed in and is null. Also switch selects to use plural if available, and singular as back up.
2. Switch inserts for new loot to insert either singular or plural, if neither matches to existing. Make singular in javascript as optional, and send either singular or plural depending on amount. (update the checks for it being filled in)

**Comment by DevJackSmith** [comment]
Another idea is to start using ids from the link for the loot as a unique identifier, that will also help correspond singular to plural. The ids come as strings https://www.mousehuntgame.com/item.php?item_type=dragon_scale_crafting_item and if we want to query the server, we can get the numeric also.
Example:
<a class="loot" title="" href="https://www.mousehuntgame.com/item.php?item_type=dragon_scale_crafting_item" onclick="hg.views.ItemView.show('dragon_scale_crafting_item'); return false;">Dragon Scales</a>
turns into
https://www.mousehuntgame.com/i.php?id=2434

Credit: plasmoidia

**Comment by DevJackSmith** [comment]
maybe we should clarify the goal we are trying to achieve with this. In my opinion it should be:
1. not have to manually manage corner cases = automate this piece of code
2. allow people to search by either name if possible

with the requirement to have same id for both names of the same item (avoid duplication in other words)

**Comment by AardWolf** [comment]
This is a mouse that dropped cloud curd. I'm curious about when one drops something like a chrome charm that's not in the HUD.
```
        "render_data": {
          "image": {
            "val": "https:\/\/www.mousehuntgame.com\/images\/mice\/thumb\/579ab1f589b7145888542e9554d3f270.gif?cv=246",
            "href": "https:\/\/www.mousehuntgame.com\/images\/mice\/large\/e7b09d9c6c3178970d71f2285a9821f0.jpg?cv=246"
          },
          "entry_id": 104192,
          "mouse_type": "kite_flyer",
          "css_class": "entry short active catchsuccessloot luckycatchsuccess",
          "entry_date": "9:05 am",
          "environment": "Floating Islands",
          "entry_timestamp": 1601211926,
          "text": "I sounded the Hunter's Horn and got <font class='luckyCatch'>lucky<\/font>!<br \/><br \/>I caught an 11 oz. <a href=\"https:\/\/www.mousehuntgame.com\/\" onclick=\"javascript:hg.views.MouseView.show('kite_flyer'); return false;\">Kite Flyer Mouse<\/a> worth 25,000 points and 980 gold.<br \/><br \/><b>The mouse also dropped the following loot:<\/b><br \/>2 <a class=\"loot\" title=\"\" href=\"https:\/\/www.mousehuntgame.com\/item.php?item_type=cloud_curd_crafting_item\" onclick=\"hg.views.ItemView.show('cloud_curd_crafting_item'); return false;\">Cloud Curds<\/a>"
        },
```

cloud_curd_crafting_item - this is in the `inventory` object that was returned. `inventory.cloud_curd_crafting_item.item_id` is 3047

So - we can get the short name from the item_type in the journal log. We can use the short name to get the item id from the inventory section. I suggest if we go this route (and I think it's the better option) we add short_name and hg_item_id to the loot table. We can confirm existence of an item by short name, then item id, then name. As we clean up the loot table and get those fields populated we can fix plurals.

After such a change:
- First loot drop for existing entry:
  1. Check for short_name. It will not exist
  2. Check for hg_item_id. It will not exist (Skip this if it wasn't found in the inventory section)
  3. Check for loot.name. It will exist -- update row to add short name and hg_item_id values

- Subsequent loot drops
  1. Check for short_name. It will exist. Use the resulting internal loot.id.

The table then has an internal ID which is unchanged from before. It has the short name, it has the hitgrab internal ID, and it has a string name for the item. We can then edit this string name to be consistently singular or plural.

Downside: Looking up plural loots is not solved (if we go with singulars). Proposal: We still add the pluralization table and the loots list returns our internal ID for both flavors of the text.

**Comment by DevJackSmith** [comment]
i don't think we need both short_name and hg_item_id. If we can reliably get the latter, i suggest we use short_name. Either one works, it's just a matter of storage space, and size = speed of all the queries/requests later. And yes, we still do the steps i described to get both plurals and singulars. I don't think we need another table. We can handle it in the loot table in my opinion.

**Comment by DevJackSmith** [comment]
i believe this has been done, just need to get rid of our id, and verify we already using hg_item_id

**Comment by AardWolf** [comment]
I think this is all complete @DevJackSmith ?
