### ISSUE TITLE
Report confidence intervals

### ISSUE THREAD

**Issue by mistotebe** [m-h-c-t/mh-hunt-helper#175]
When deciding where to hunt for a certain mouse/loot, a lot of nonsensical/rare combinations pop up in the top of the list. If there was a way to visually separate them based on the perceived accuracy of the line, that would help weed out those.

Looking at https://github.com/m-h-c-t/mh-hunt-helper/blob/main/src/searchByItem.php#L88 we already have all the info we need to report to the page, since confidence interval for this distribution would be `= z * sqrt( h.rate * (1 - h.rate) / h.total_hunts )` where z is ~2 for 95% confidence interval, this could all be done in the SQL layer relatively cheap, haven't tested of course.

Then we could color the line (the more accurate the greener :)) or display a confidence interval instead and sort by that?

**Comment by DevJackSmith** [comment]
interesting idea. I'm not sure about sorting at least at first, but calculating it, storing it, and displaying something like could probably be done. Also this doesn't have to be done on db layer, but could be done on client side in javascript.

**Comment by AlexClaxton** [comment]
> Looking at https://github.com/m-h-c-t/mh-hunt-helper/blob/main/src/searchByItem.php#L88 we already have all the info we need to report to the page, since confidence interval for this distribution would be `= z * sqrt( h.rate * (1 - h.rate) / h.total_hunts )` where z is ~2 for 95% confidence interval, this could all be done in the SQL layer relatively cheap, haven't tested of course.

The low fidelity version is to just have N < 100 is low confidence, < 500 is medium confidence, <1000 is high confidence, and >=1000 is very high confidence

**Comment by mistotebe** [comment]
How about exposing the actual interval somehow? Is there a way to have a column show '1%-5%' and sort like '1%'? Then sorting by the chance would pick up the ones we have most data (narrowest confidence interval) in first and ignore the flukes etc.

**Comment by DevJackSmith** [comment]
lets discuss this more on discord, that might be faster. Bring it up in #community-tools, there are quite a few people who can help.

**Comment by DevJackSmith** [comment]
lots of hunts doesn't mean it's the best way either. To avoid non-sensical ones, we now filter out everything <100 hunts sample size
